services:
  - type: web
    name: autoai-scout
    env: docker
    plan: free
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
